//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModelClass.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartID { get; set; }
        public string DepartName { get; set; }
        public string DepartSN { get; set; }
        public string DepartCode { get; set; }
        public string Memo { get; set; }
    }
}
