//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModelClass.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFDBModelEntities : DbContext
    {
        public EFDBModelEntities()
            : base("name=EFDBModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<OrgMaster> OrgMaster { get; set; }
        public virtual DbSet<PartsMaster> PartsMaster { get; set; }
        public virtual DbSet<PODetail> PODetail { get; set; }
        public virtual DbSet<POEntity> POEntity { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectOrg> ProjectOrg { get; set; }
        public virtual DbSet<PODetail_View> PODetail_View { get; set; }
        public virtual DbSet<POEntity_View> POEntity_View { get; set; }
        public virtual DbSet<ProjectOrg_View> ProjectOrg_View { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserDepartment_View> UserDepartment_View { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
    }
}
