//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModelClass.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODetail_View
    {
        public int PODetailID { get; set; }
        public int POID { get; set; }
        public int PartsID { get; set; }
        public int Qty { get; set; }
        public decimal SalePrice { get; set; }
        public decimal OrderPrice { get; set; }
        public string Memo { get; set; }
        public string PartsCode { get; set; }
        public string PartsName { get; set; }
        public string BrandPartsCode { get; set; }
        public string BrandPartsName { get; set; }
        public string PONo { get; set; }
    }
}
