//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModelClass.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class POEntity_View
    {
        public int POID { get; set; }
        public string PONo { get; set; }
        public int SupplierID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int MasterID { get; set; }
        public int ProjectID { get; set; }
        public string MasterOrgSN { get; set; }
        public int CreaterID { get; set; }
        public string Username { get; set; }
        public string SupplierOrgSN { get; set; }
        public string ProjectName { get; set; }
        public int UserID { get; set; }
        public string Memo { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
    }
}
