//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModelClass.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDepartment_View
    {
        public string DepartName { get; set; }
        public string DepartSN { get; set; }
        public string DepartCode { get; set; }
        public string OrgSN { get; set; }
        public string OrgName { get; set; }
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Role { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int MasterID { get; set; }
        public int DepartID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string Memo { get; set; }
        public Nullable<int> Gender { get; set; }
        public string GenderName { get; set; }
    }
}
